server:
  port: 8083
  forward-headers-strategy: framework

releng:
  url: http://${TEST_MOCK_SERVER_HOST}

# These values are not used in tests. They are only needed because they are required in the application configuration
jira1:
  host: http://localhost:1080
  username: admin
  password: admin

components-registry-service:
  url: http://components-registry-service:4567
