shared:
    database:
        type: postgresql
        driver: org.postgresql.Driver
        url: jdbc:postgresql://dms-ft-artifactory-db:5432/artifactory
        username: artifactory
        password: secret
